-- ============================================================================
-- Migration: Create flashcards table with RLS policies
-- Created: 2025-10-21 17:00:00 UTC
-- ============================================================================
-- Purpose:
--   This migration creates the core flashcards table for the 10xCards application.
--   It includes:
--   - Main flashcards table with spaced repetition metadata (SM-2 algorithm)
--   - Row Level Security (RLS) policies to ensure users can only access their own data
--   - Composite index for optimizing due date queries
--   - Trigger for automatic updated_at timestamp management
--
-- Affected tables:
--   - public.flashcards (created)
--
-- Special notes:
--   - Uses Supabase auth.users for user management
--   - Implements cascade deletion when users are removed
--   - RLS policies are granular: separate policies for each operation and role
-- ============================================================================

-- ensure uuid extension is enabled for uuid_generate_v4()
create extension if not exists "uuid-ossp";

-- ============================================================================
-- table: public.flashcards
-- ============================================================================
-- the central table for storing all flashcard data, including content and 
-- spaced repetition metadata based on the SM-2 algorithm
-- ============================================================================

create table public.flashcards (
  -- primary key: unique identifier for each flashcard
  id uuid primary key default uuid_generate_v4(),
  
  -- foreign key: links to the user who owns this flashcard
  -- on delete cascade ensures all flashcards are deleted when user is deleted
  user_id uuid not null references auth.users(id) on delete cascade,
  
  -- flashcard content: front side (question)
  -- constrained to 1-500 characters
  front text not null check (char_length(front) > 0 and char_length(front) <= 200),
  
  -- flashcard content: back side (answer)
  -- constrained to 1-1000 characters
  back text not null check (char_length(back) > 0 and char_length(back) <= 400),
  
  -- flag indicating if this flashcard was generated by ai
  created_by_ai boolean not null default false,
  
  -- spaced repetition metadata: number of successful recalls in a row
  repetition integer not null default 0,
  
  -- spaced repetition metadata: number of days to wait before next review
  interval integer not null default 0,
  
  -- spaced repetition metadata: easiness factor for SM-2 algorithm
  -- determines how quickly the interval grows
  efactor numeric not null default 2.5,
  
  -- the date when the flashcard is scheduled for next review
  -- defaults to now, making new cards immediately available for review
  due_date timestamptz not null default now(),
  
  -- timestamp of when the flashcard was created
  created_at timestamptz not null default now(),
  
  -- timestamp of the last update, managed automatically by trigger
  updated_at timestamptz not null default now()
);

-- ============================================================================
-- indexes
-- ============================================================================

-- composite index on user_id and due_date
-- purpose: optimizes queries fetching flashcards due for review for a specific user
-- typical query: select * from flashcards where user_id = '...' and due_date <= now()
create index flashcards_user_due_date_idx on public.flashcards(user_id, due_date);

-- ============================================================================
-- row level security (rls)
-- ============================================================================

-- enable rls on the flashcards table
-- this ensures that all queries are subject to rls policies
alter table public.flashcards enable row level security;

-- ----------------------------------------------------------------------------
-- rls policies for anon role (unauthenticated users)
-- ----------------------------------------------------------------------------
-- rationale: anonymous users should have no access to flashcards data
-- all operations return false, effectively denying all access

-- anon: select policy
-- denies anonymous users from viewing any flashcards
create policy "anon_users_cannot_view_flashcards"
on public.flashcards
for select
to anon
using (false);

-- anon: insert policy
-- denies anonymous users from creating flashcards
create policy "anon_users_cannot_create_flashcards"
on public.flashcards
for insert
to anon
with check (false);

-- anon: update policy
-- denies anonymous users from updating flashcards
create policy "anon_users_cannot_update_flashcards"
on public.flashcards
for update
to anon
using (false)
with check (false);

-- anon: delete policy
-- denies anonymous users from deleting flashcards
create policy "anon_users_cannot_delete_flashcards"
on public.flashcards
for delete
to anon
using (false);

-- ----------------------------------------------------------------------------
-- rls policies for authenticated role (logged-in users)
-- ----------------------------------------------------------------------------
-- rationale: authenticated users can only access their own flashcards
-- all policies check that auth.uid() matches the flashcard's user_id

-- authenticated: select policy
-- allows users to view only their own flashcards
create policy "authenticated_users_can_view_own_flashcards"
on public.flashcards
for select
to authenticated
using (auth.uid() = user_id);

-- authenticated: insert policy
-- allows users to create flashcards only for themselves
-- with check ensures user_id is set to the authenticated user's id
create policy "authenticated_users_can_create_own_flashcards"
on public.flashcards
for insert
to authenticated
with check (auth.uid() = user_id);

-- authenticated: update policy
-- allows users to update only their own flashcards
-- using clause prevents viewing others' data, with check prevents changing ownership
create policy "authenticated_users_can_update_own_flashcards"
on public.flashcards
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- authenticated: delete policy
-- allows users to delete only their own flashcards
create policy "authenticated_users_can_delete_own_flashcards"
on public.flashcards
for delete
to authenticated
using (auth.uid() = user_id);

-- ============================================================================
-- trigger function for updated_at automation
-- ============================================================================

-- function: handle_updated_at
-- purpose: automatically updates the updated_at column to the current timestamp
-- whenever a row is modified
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  -- set the updated_at column to the current timestamp
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- trigger: on_flashcards_update
-- purpose: calls handle_updated_at function before any update operation
-- on the flashcards table
create trigger on_flashcards_update
  before update on public.flashcards
  for each row
  execute function public.handle_updated_at();

-- ============================================================================
-- end of migration
-- ============================================================================
