-- ============================================================================
-- Migration: Create generations table and link to flashcards
-- Created: 2025-10-21 20:42:00 UTC
-- ============================================================================
-- Purpose:
--   This migration creates the generations table for tracking AI flashcard 
--   generation events and links it to the existing flashcards table.
--   It includes:
--   - Immutable generations table for tracking AI generation events
--   - Foreign key generation_id in flashcards table
--   - Indexes for optimizing generation queries
--   - Row Level Security (RLS) policies for generations table
--
-- Affected tables:
--   - public.generations (created)
--   - public.flashcards (altered - added generation_id column)
--
-- Special notes:
--   - Generations table is immutable by design (no updated_at column)
--   - generation_id in flashcards is nullable to support manual flashcards
--   - ON DELETE SET NULL preserves flashcards when generation is deleted
--   - Cost stored with 6 decimal precision for accurate API cost tracking
-- ============================================================================

-- ============================================================================
-- table: public.generations
-- ============================================================================
-- immutable table for tracking AI flashcard generation events
-- each record represents a single AI generation session
-- ============================================================================

create table public.generations (
  -- primary key: unique identifier for each generation event
  id uuid primary key default uuid_generate_v4(),
  
  -- foreign key: links to the user who initiated the generation
  -- on delete cascade ensures all generations are deleted when user is deleted
  user_id uuid not null references auth.users(id) on delete cascade,
  
  -- the source text provided by the user for AI generation
  -- constrained to 1000-10000 characters as per PRD requirements
  source_text text not null check (
    char_length(source_text) >= 1000 and 
    char_length(source_text) <= 10000
  ),
  
  -- optional context/topic provided by the user to improve AI generation quality
  -- nullable field allows users to generate without providing context
  context text,
  
  -- identifier of the AI model used for generation
  -- examples: "gpt-4", "claude-3-sonnet", "gpt-3.5-turbo"
  -- stored as text for flexibility to support different AI providers
  ai_model text not null,
  
  -- time taken to generate flashcards in milliseconds
  -- must be non-negative, useful for performance monitoring
  generation_time_ms integer not null check (generation_time_ms >= 0),
  
  -- number of flashcards successfully generated in this event
  -- denormalized for quick analytics without joining to flashcards table
  -- must be non-negative
  flashcards_generated_count integer not null check (flashcards_generated_count >= 0),
  
  -- cost of the API call in USD
  -- stored with 6 decimal precision for accurate tracking of small API costs
  -- default 0 allows for free tiers or models without cost
  -- must be non-negative
  cost numeric(10,6) not null default 0 check (cost >= 0),
  
  -- timestamp of when the generation event was completed
  -- no updated_at column as this table is immutable by design
  created_at timestamptz not null default now()
);

-- ============================================================================
-- alter table: public.flashcards
-- ============================================================================
-- add generation_id column to link flashcards to generation events
-- ============================================================================

-- add generation_id column as nullable foreign key
-- nullable allows for manually created flashcards (not generated by AI)
-- on delete set null preserves flashcards even if generation record is deleted
-- this maintains data integrity while allowing generation history cleanup
alter table public.flashcards
add column generation_id uuid references public.generations(id) on delete set null;

-- ============================================================================
-- indexes for flashcards table
-- ============================================================================

-- index on generation_id
-- purpose: optimizes queries fetching all flashcards from a specific generation event
-- typical query: select * from flashcards where generation_id = '...'
-- supports null values for manually created flashcards
create index flashcards_generation_id_idx on public.flashcards(generation_id);

-- ============================================================================
-- indexes for generations table
-- ============================================================================

-- index on user_id
-- purpose: optimizes queries fetching generation history for a specific user
-- typical query: select * from generations where user_id = '...'
-- use cases: analytics, user generation history, cost tracking per user
create index generations_user_id_idx on public.generations(user_id);

-- index on created_at with descending order
-- purpose: optimizes queries fetching recent generations in chronological order
-- typical query: select * from generations order by created_at desc limit 10
-- use cases: admin dashboards, recent activity feeds, generation history
create index generations_created_at_idx on public.generations(created_at desc);

-- ============================================================================
-- row level security (rls) for generations table
-- ============================================================================

-- enable rls on the generations table
-- this ensures that all queries are subject to rls policies
alter table public.generations enable row level security;

-- ----------------------------------------------------------------------------
-- rls policies for anon role (unauthenticated users)
-- ----------------------------------------------------------------------------
-- rationale: anonymous users should have no access to generations data
-- all operations return false, effectively denying all access
-- generations contain sensitive user data and API usage information

-- anon: select policy
-- denies anonymous users from viewing any generation records
create policy "anon_users_cannot_view_generations"
on public.generations
for select
to anon
using (false);

-- anon: insert policy
-- denies anonymous users from creating generation records
-- only authenticated users can trigger AI generation
create policy "anon_users_cannot_create_generations"
on public.generations
for insert
to anon
with check (false);

-- anon: update policy
-- denies anonymous users from updating generation records
-- generations are immutable, but this policy prevents any attempts
create policy "anon_users_cannot_update_generations"
on public.generations
for update
to anon
using (false)
with check (false);

-- anon: delete policy
-- denies anonymous users from deleting generation records
create policy "anon_users_cannot_delete_generations"
on public.generations
for delete
to anon
using (false);

-- ----------------------------------------------------------------------------
-- rls policies for authenticated role (logged-in users)
-- ----------------------------------------------------------------------------
-- rationale: authenticated users can only access their own generation records
-- all policies check that auth.uid() matches the generation's user_id
-- this ensures data isolation and privacy

-- authenticated: select policy
-- allows users to view only their own generation records
-- enables users to review their generation history and costs
create policy "authenticated_users_can_view_own_generations"
on public.generations
for select
to authenticated
using (auth.uid() = user_id);

-- authenticated: insert policy
-- allows users to create generation records only for themselves
-- with check ensures user_id is set to the authenticated user's id
-- prevents users from creating generation records for other users
create policy "authenticated_users_can_create_own_generations"
on public.generations
for insert
to authenticated
with check (auth.uid() = user_id);

-- authenticated: update policy
-- allows users to update only their own generation records
-- note: while the table is designed to be immutable, this policy allows
-- for edge cases such as correcting metadata or administrative adjustments
-- using clause prevents viewing others' data, with check prevents changing ownership
create policy "authenticated_users_can_update_own_generations"
on public.generations
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- authenticated: delete policy
-- allows users to delete only their own generation records
-- enables users to clean up their generation history if desired
create policy "authenticated_users_can_delete_own_generations"
on public.generations
for delete
to authenticated
using (auth.uid() = user_id);

-- ============================================================================
-- end of migration
-- ============================================================================
